# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'octokit', '~> 8.0'
gem 'tty-prompt', '~> 0.23'
gem 'tty-table', '~> 0.12'
gem 'tty-spinner', '~> 0.9'
gem 'pastel', '~> 0.8'
gem 'dotenv', '~> 3.0'

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
end
