#!/usr/bin/env ruby

datafile = ARGV[0]


lines = File.read(datafile).split()

puts lines.size

lines.each_cons(2) do |a|
  puts a[0].to_i - a[1].to_i
end

File.read(datafile).split().each_cons(2) { |a| puts "%{a[0].to_i - a[1].to_i} : %{a[0]} - %{a[1]}" }
