#!/usr/bin/env bash

[[ -f ~/.ansi.functions ]] && . ~/.ansi.functions || ( echo -e "🧚 Help on the way" && exit 127 )


echo -e "🛟 "

echo "https://raw.githubusercontent.com/morganism/tools/refs/heads/master/message"
curl "https://raw.githubusercontent.com/morganism/tools/refs/heads/master/message"

