#!/bin/bash
#
# i make a symlink for each file in ./bin to $HOME/bin
#
[[ -f ~/.ansi.functions ]] && source ~/.ansi.functions #&& echo "Yes"
[[ -L ~/.ansi.functions ]] && source ~/.ansi.functions #&& echo "YesL"

HOME_BIN="$HOME/bin"         # the bin dir
THIS=$(realpath $BASH_SOURCE)
THIS_FILE=$(basename $THIS)
TOOLS_DIR=$(dirname $THIS)

usage() {
  echo -e "${IWhite}Usage: ${White}${THIS_FILE}${Reset} ${IBlack}[-D]${Reset}"
  echo -e "       ${IBlack} -D dry run .. do not link anything just print what would be done.${Reset}"
  echo -e "       ${IBlack} -h Help ${Reset}"
  exit
}

DRY_RUN="NO"
if [[ "$1" =~ ^- ]]; then
  [[ "$1" =~ -h ]] && usage
  if [[ "$1" =~ -D ]]; then
    DRY_RUN="Y"
    echo -e "${Green}${On_Grey_4}Dry Run Mode${Reset}"
  fi
fi


cd $TOOLS_DIR

echo -e "${IBlack}moving to correct directory: ${White}$TOOLS_DIR${Reset}"

echo -e "${IBlack}linking bin files${Reset}"
cd $TOOLS_DIR/bin
for f in $(find . -type f -o -type l)
do
  FILE="$(realpath $f)"        # the file in git
  NAME="$(basename $f)"        # st the name 
  TARGET="${HOME_BIN}/${NAME}" # the target 1

  #[[ -f "$TARGET" ]] && [[ $(file "$TARGET" | grep "$FILE") ]] && rm "$TARGET" && [[ "$?" = "0" ]] && echo -e "${Green}clean${Reset}" 

  COMMAND="ln -sf $FILE $TARGET"
  if [[ "$DRY_RUN" =~ "Y" ]]; then
    echo -e "${Green}${On_Grey_4}${COMMAND}${Reset}"
  else
    echo -e "${iWhite}${COMMAND}${Reset}"
    $COMMAND
  fi
done
cd ..
echo -e "${IBlack}linking dotfiles${Reset}"
cd $TOOLS_DIR/dotfiles
for f in $(find . -type f -o -type l | grep -v $0)
do
  FILE="$(realpath $f)"
  NAME="$(basename $f)"

  if [[ -e "${FILE}" ]]; then
    #if [[ -e "${HOME}/${NAME}" ]]; then
      #rm "${HOME}/${NAME}"
    #fi

    COMMAND="ln -sf $FILE $HOME/$NAME"
    if [[ "$DRY_RUN" =~ "Y" ]]; then
      echo -e "${Green}${On_Grey_4}${COMMAND}${Reset}"
    else
      echo -e "${iWhite}${COMMAND}${Reset}"
      $COMMAND
    fi
  fi
done
