#!/bin/bash
#



THISSCRIPT=$(realpath $0)
THISDIR=$(dirname $THISSCRIPT)
echo $THISDIR
exit
cd ${HOME}/bin
for s in $(echo "bak hex2dec httpsd lswin.py json_prettify.rb os randomhex rsa2pem")
do
  ln -s ${THISDIR}/bin/${s} .
  echo "linked ${s}"
  echo "rm ${HOME}/bin/${s}" >> undo
done
chmod 755 undo

cd ${THISDIR}
