# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sqlite3', '~> 1.7'
gem 'thor',    '~> 1.3'

group :development, :test do
  gem 'rspec',   '~> 3.13'
  gem 'rubocop', '~> 1.65', require: false
end
